language: node_js
env:
  global:
  - SINGPATH_RULES_FB_ID=singpath-travis
  - secure: KHoHXHYdb+AmfmWabxvExcdrNu2x0VrzQtobgtXFaKAISO3hqGI1L3KjRDJHj9jZA8TLPrmJMSsEcaP23VJovudRUPesfseLacKoMhMqwmnClYbiB1A8QERJJRbm88G0c0ocfoK0E7w4DsiqICFX9FyLz3VYSOmSugdlTOHcgB3B6Q+jCDhFZedTaNvPYFjNAvYMR77imfpS+OPs0VpznQ3A2PPelfmuWTgiGZVndseWXqEV83VhaSz5rv8WsgCQpe9wcBor5uCgFBALVVdpTPK5mBIGThbFAD2SLQrMvdUCDY1uFdVYxtxsLCgd+DiSdXFxmd+tRJFP65KyBknKNwmWTQr8fe5E2VHU0McP5iFZgO8BBpeUU09bHOrd6vFKMtsEyZtGPHV3aV14N1LkstGxRtsr12Ag1kWMtWIZApYYA3uN5cyQ7eCGKkR+wilA/N9v5g3ci2CL8scd/vwNXV6m/CYRYlrC4JqMiQnDp1TLmKf6sygdB+XESZGB9OGRaUncuQh2zfUT9cfNf2Pf8mc62NvqH98OjxGL0KQjK6hEZUdrKddhRycACJHMfw9HkZtIIvcEoezF82Knizaae/mFai5+nmmNWhK1/QbGqGAQsDkrpdb6sm+ur70Wf9SCfNHuC0QSlZrRqECU7Swz4GIEtAQIXUj6pEeKnh4yrxA=
  - secure: W5YBUQVWnBqtYDC9B7zyh1FbDz8ZeP4/gkjFr86gQCPwAMAEKkTy88TqqoRIPL0P9/Mx6l9gACfiiMES0H2Mh0DPalBbP3Ako7FYBa/PTGkEJdS6c3i3L0dNfDJ3HhkkrJlYqSYncgqMOOFDjTq9A/WNGncIoyv9VyBWS/5ARBmZKg9+yqr4da1FsjazfY12iS4bsfIvdrkfqwloqBhJp5rYz4wZE6XwTMT8e7o7AHjgzOZBBcQ/NjpJo8ejRg1CKvUYsxKw/P6nRgQAv+2meZocxvwyPt3g3Z6oZWMCAn5y3fV22nEJI//mpza6GR9Q+5tZ8rjENRPbTIAGWqb+RC0N5t3p0oTW7cjRG8rx0gys5Qw36YeQoc0odCBd96hkwOCh12VD8SSysrXn+8hPa9cDMdvKqFRj0h+IfNaRyr/IVD86XKGu6gXjS7Hd7NRA/1kdN7/dwXJ7Ez34IcNKbH523r7646gNvy6B7DIAHt/vVBYWt7+g5ecNB1mtoVIN/6Z66/8Rg4DGZtnwSsyQFUMkawmpHnkU1V3RNpnGkuud6K7VCchy2QRQcpBbKhhG3+RFQsZCcKO0MITEN3YKzNFg5N2eQrWQvhLTrSJtA5tHO8Cy42wJdVPD6KRrc1ONwcKb4BUT57vuftbaxAk9uTwj5YuIXuBlqdUQBd6FHWM=
node_js:
- '4.1'
install:
- npm install
script:
- make test
- test -z "$SINGPATH_DEPLOY_TOKEN" || npm run upload-rules-ci
- test -z "$SINGPATH_RULES_FB_SECRET" || npm run test-e2e
