language: node_js
env:
  global:
  - SINGPATH_RULES_FB_ID=singpath-travis
  - secure: pFgUzjTjBpxnK09BIbXBNCqwderheoG8MT3JZpaipdFn2yuu90ZhSM+KgNSjaJtFRKsq5LAK/tioTPrjOTitXAwAVo+Dd93YgvPh01X9LmPrnYPYx8XmE7P4fV3/ODvMuCMPyQAqPSkJhFrWD0AKZ4f0kc8JQVl90C1ekpp0o7Xi2mtzMyQmt8YiRZTZl4dJel+sw3dsGBFWi/jJE613sngd3pGKX33hz1jfc7xipTOzUQrIGc8V+fML+/kMkf+nYVm/hIqDWxQnstuoF65TO0alGAZflFgFNI2LBjyIe4FF414mrKQcYsKIDkbYDx1+7I8zvHybDGLzz8SOi4ynlHeXrh+YlvcLLctfhrg+dvm0MEzTX2lmsCiIcwjbgOzb3DoHRz0rtc+ZT2+YCucvHpR5COQBt6e387MRY98F/F8jFM30O/d7coaRwtu3qqkqzQ3EFeY4eXXWnUVEuAnccbOQOcppVEfTPpGUaw8+/6a4kmonVjFQ3J+wWpzxCpb5WamI780eHI44hhcQUIEs9TniYvJ64nxRBC4xMzIaQB6BgYthev1hTu/eEIX/2pXGRZtw5ebxXMiz42D02J4zyfb9OqV0nDadZnlzVz6C0J8eHEuPZJaP5OpPy7oONF2yZOwuIIvCz70jV0am67QotbM+xMPiqlPkZjZdiijrZfs=
  - secure: PUC1tRKeWjMFfODLqnNoMzjciReCPy86cnX+4ZzltZlrsMdzXBdhZ46BjOrQb/qSSL+N3i7axqZ1Ibr3N+mbHc6firYKUM+yO+7tjBUYPS/F64cAu/nXdfqci/z5PcE2z10FKYpGjjucHvX2YN2BbEtaIk/BNcc0FJWtSdT5jaJFVevJKojQIdnlRX9ziCQyiTaAYP2EEvXQHulmof8VIvKiTkrBtWiaYFBaTzg3PiqwFeNwpRwCDXgzonGIJO2QcVFtIl3CdFbjbn2LwPWkYavjGvDA/h2nc/piNhA3z0w4wJwn+s50uJoAZpptPPOM3DZYA4AkGbbpeDTmYUvVV24WAy3/YDw7Z3okFX7dxbLU3QbQdskkLYRL8FdhIXkkhDWaHJtbdHbwULjTuYku4HlufMS0uhDq5saawnrggmMyQZKwMYG+hsQvOzjGIa09X3xLIA68MxjtB/1BN3k2u20yJEK5RSs9kbsFwx8z8BAG5tt8jvXRiXJ5ldgJgJzq9/NNQ7hEAR6eMEbXJjyDd7DSR3sPbah4aPawca6qPocPCL3sNbak4kMXUos3QX4mLFBzmGZO4uEtYXGI2O/4eHEfeGMHhmVLb5kuodnkT+N/LaDED2cDBDJpViOv+/Jwi0N2EEDkhZH/NkIN4QtvZvrTVhE/SrNjetoY9icmNig=
node_js:
- '4.1'
install:
- npm install
script:
- npm test
- npm run coveralls
- test -z "$SINGPATH_DEPLOY_TOKEN" || npm run upload-rules-ci
- test -z "$SINGPATH_RULES_FB_SECRET" || npm run test-e2e
