language: node_js
env:
  global:
  - SINGPATH_RULES_FB_ID=singpath-travis
  - secure: MqHzRdr0STNuj/ayAFyMe4UxRhXfHJ/qVuGPEW1RoTQ7ANwE0+VhydVYwkpKFRkulzkcwIh0SXOp6SWkHC3qRJC2NH1hp9/0mIGP0fUrvMdDlQoNJd4jJBZ/EdA3YNbx8BUFWXE33GNbS/rBPcYXuasnLpjytbAb/7/zXX7MEQ1LMP5Jeq/FqyTje5mE5ytaOylKqKRqD3pcat0dJwp+uqRsEroC+2zgLsaeIJ61OJYF7gdragGPRisNLbj6vbWD1KLL+OdPKINefFEygmrajl6nQyDBYSTw6t+ZGvfm4gTt8xBvt+NnRuN6dEWMicFSoHTuU7NBXkMplnYh2kbsZZitqYTXhj0XDffHQ9grOIqO/yoAIKd6jsEMWp/eDdcBHqMAnZp0wkKDB+Zdo3einc0FOLAnFJYQaP0WsgEDt9V+P1W7BR4Htla/Lz3atRYx5z5RiK3gDEgLTRjJo7Qq4X6HffHyinckghhUgpIS+L/ov1qzRnTG3fiJAZlweW083bjre9crFm1u5qCCI03/IHZtURz4J/tBIK/9sV/TE56wEJi+aRR7tqbWD/odc8gLt1TBzoidRYWIKu4zJnwKdTjNcfjr31pKjkX/c0V4q2XAU2+oecmr6LBSVSzGiWe2HVH96ReyN7NUKul6EERIskLYJ6y3fgFo+/T7tO5s4fM=
  - secure: FUaoDFXbBCxYDhpTIxNZ+R38TceTUU8u478a+Ydcn+VY7sktHt/YcB7RQNawmd/6daxbWDhdC+S6sPcHb8W8VKVwDk74ErvZkC14YThmQitY8jFQitN4vsdonu7285oLx3L0LWWNsIIIlXMP1/5vae66nrnslkGpeo2IjZULY/3KjnbJcS6P9HeLATCwDLh2Cfayb6C2LPU4aAie+kQS/XDFO81LWloq3d7GvOUFlmHgGsmMfjfmOQ183nBuB0j+nIqyc8rbcMvLGGr+cQEV+kCI/LaUhCV8M+NXLM7Hsn5oY4fIzg7X4mB/VjrAGsVDjszhnP9BhdDqZvZexfCIqtO56/LCxcdNrABFbV9ax54CikXh+3NcqcwN0ZDaJUEcEEE9PLl4cEdUHvlW3s3rArYWMKIAcSwfMoQacJDeQ8N+rQ/FudxfHJZ36rPkNbFDphfyZRzEVslEvkbytPfl0zXgYTqHGa5LMatkLzBuZjGpYL/M6SCz5s/1GTevwy9WmQSRdCDPW7b8eU6p+RZoFTnb7+P5p2VR5JtihQT0L23U8trxEA24JuecdNwoz4DcJkXgLe97jSmknFkqCcEumOinqkxW/evyl6DNvU2uYCpstFGM6FXf6VGRiJnDgxUcvek/Ag6JAEBuOvT3Cg7rgB3/HOxbCsq0ygO2kmHmApM=
node_js:
- '4.1'
install:
- npm install
script:
- make test
- test -z "$SINGPATH_DEPLOY_TOKEN" || npm run upload-rules-ci
- test -z "$SINGPATH_RULES_FB_SECRET" || npm run test-e2e
