language: node_js
env:
  global:
  - SINGPATH_RULES_E2E_FIREBASE_ID=singpath-travis
  - secure: LyMDM0+lar9SSz1kqIZMLPUSEBvmeHilkKKik4MfJvngLvJm8KdyqNLoy9veEWzVKUe58JeRCsNXR6igbZu/055wJaAiT1eT63EeRSakAKf/xeqcU3kp1hULDoKsYNYDy2+I6nMs6+buGZS1ghicMJmVSp1PmPHgyKh8RjsvWnVp/Y+oTTtFKJxCiQEVp+tXfWeCaqoV2p3g5TM+1g4Qwp5aVQYiWdQ5DzF3scnYtt9gLdTMb1iKFB9MkkB3iqAqdK9QfCrEKfY/Mkxv2Dxrgb3tUaBRT1T0nekhr+OJpUUph1S51lyk7NP3BW9SGB8YWCsH18sUlwMeW46NM6LLVaHmQKNzcStzu5xj1ze0kh/jGidD/owPHq4wUA37b8oF7pgFZOtUYzudu67PnDpLe2STigpSYr4iy/66GCA6COBKnbkf+kv2LRka7pIS5kwenAjlqKEd2DBWWaZRFBoh5BkRJD/nODReJCDUW3Y8Y8nu3tdrUCtsZo0r7YdNdW95/Y53MveMLY4AUwrMr+OOZrOJFX0FUqZrnUOqYk5AkMLojJGtL1Pg+2oMESvWKo2JGdPPxQ2srfW70ibZNfwHHEla+fF+irs/FQIoi8IVhca7gvhW2m6Dklr/hxHdv/s+gk9SgRlP7EeDV2UtM6hkyA6jztQQboQhH4QtEctYfeU=
node_js:
- '4.2'
install:
- npm install
script:
- npm test
- npm run coveralls
- test -z "$SINGPATH_RULES_E2E_FIREBASE_SECRET" || npm run upload-rules-e2e
- test -z "$SINGPATH_RULES_E2E_FIREBASE_SECRET" || npm run test-e2e
