language: node_js
env:
  global:
  - SINGPATH_RULES_FB_ID=singpath-travis
  - secure: E0CJdA0Fuu2fJe2UbPfAr3NU+Ijgwz7kcNfWJB3hHGYOcBvS38znLvV4Oo+lWUwRQdXTrQB/awDIs49Met2VCJd47tlY4ckpPmsFW8agRiCJy3Okw/Uv21CYOfoIV5hBjZtspcvZRNF+5duVjk9civCEen8ibfcK4qr0+rHggsr+ctOQ4CjrKfsDbGof8AWP7QZVUm9A7VyzUh2ZBsEwaVBkmZQeot4joZIjyDPH2gJFJyZBkMMft9BVOLieEJyi4ckJOmIFt8pO+Ajjt/86aPx7+GDrkecZ7ReCflBlA0dkr51Wmtx2lolvJS2C9kHjdkUBw0du0DTZEB8O+ppODLsGmIARbbC7pjTMYkKp+tKMccyNLvSxzrhALjVazLPwFxFsMpE7NUL9veKyHQNfYZpBUDMAkQJH7ODC/0OkWQwfW81L1I0MjRGV+pNmyVlhidEgMeFIGrV8r0XthtbxIYwJ0gZ8Tl3VmYzobfa3COkzAL7X4DbC8bEqjRxs+QchKTUSx4hk1kPHI4NYdJ7D9OSm9/WVUm5wrnZhK3ZrYzlcXNtuyU3Iwfkfx/1mMbdbY+kZDtCuv1ZQm2tTcLnB9aMBPrLjGo8XHbitoed+3riXM+x4QjKby92Ya4XKq6XOF9Uek5egCnoMEZnPU4wntN50wjR9C1QFpKK3rUETHOw=
  - secure: cTbLkxwy4HF1zqWWkWK6aXzR9y9trMpnESwZHP2+0s0k4yDl+Z6upKdRDzsq4f8DOFAAckhA/eEWwfp+56tcrcF8A5W0ujJoIzidCBqB07Df/ytkxPO5/mNR/qy4UUqjWNJxSQvHUnhKwkTn8oGIYK/QmaG3qn6CBpFVwe3KdyKYgevAQ0ddQ4JQsmAbUVl09ThLdkDVF27UDBzvfTvIK1VppZKL9mxXxgx0sCUT/OqNH4d1kbujpZqktjnz/H5ZwxBuLtIT9Mr7avMcOjxYCmSCfhaBUHXL/9Sh82NvRtPCPYq2BDO5jLbjzPd6BgVtt9j1S7Xc5U2A7um0mqpqMpHAjKRU4PU47QDAqzJ+vQxISpBluah12Ka8rqEXKEl5+lycxk524VfJpcpVZrhkZEvmZoqIJX5ScRXv4HTKLbe1j5NGdQqMHaF9kNvkuBbWa4wjTE/mLP/+6c6HuJ4O3nnRn5JJs/EDZT51Ctgp4iQ8y54WWV15GPFPBb2RECFuFvmTMfktY+E/LRLdoCeivblvp59DZ1DHOSE3NxAsN79+sGMi+XD99V9uf4PlSY/OTinx4tvoEC/oy+b1C7hLCI9d3EJ51ExkEgF/Yw5c9HVwIi84BV8Lob9lRk7uzEiUTpsecgzzUz2koCWxOG0Xi03dya0Yaiyrk39Ln6bnYSc=
node_js:
- '4.1'
install:
- npm install
script:
- make test
- test -z "$SINGPATH_RULES_FB_SECRET" || echo '{}' > extra-rules.json && make e2e
